http://localhost:3000/cursos

###

POST http://localhost:3000/cursos HTTP/1.1
content-type: application/json

{
    "nome": "Ruby"
}


###
PUT http://localhost:3000/cursos/2 HTTP/1.1
content-type: application/json

{
    "nome": "Ruby"
}
